project:
  type: website
  output-dir: _site

execute:
  freeze: auto
  enabled: false

website:
  title: "Pooja Sukhdeve"
  site-url: "https://poojasukhdeve.github.io/"
  navbar:
    right:
      - text: "About"
        href: index.qmd#about
      - text: "Skills"
        href: index.qmd#skills
      - text: "Projects"
        href: index.qmd#projects
      - text: "Services"
        href: index.qmd#services
      - text: "Contact"
        href: index.qmd#contact

format:
  html:
    theme: cosmo
    css: styles.css
    page-layout: full
